export default {
  accordion: [
    "Accordion",
    "AccordionContent",
    "AccordionItem",
    "AccordionTrigger",
  ],
  carousel: [
    "Carousel",
    "CarouselControl",
    "CarouselNextSlideTrigger",
    "CarouselPrevSlideTrigger",
    "CarouselSlide",
    "CarouselSlideGroup",
    "CarouselViewport",
  ],
  checkbox: ["Checkbox", "CheckboxControl", "CheckboxInput", "CheckboxLabel"],
  "color-picker": [
    "ColorPicker",
    "ColorPickerArea",
    "ColorPickerAreaGradient",
    "ColorPickerAreaThumb",
    "ColorPickerChannelInput",
    "ColorPickerChannelSliderBackground",
    "ColorPickerChannelSliderThumb",
    "ColorPickerChannelSliderTrack",
    "ColorPickerContent",
    "ColorPickerEyeDropperTrigger",
    "ColorPickerSwatch",
    "ColorPickerSwatchBackground",
    "ColorPickerSwatchGroup",
  ],
  combobox: [
    "Combobox",
    "ComboboxContent",
    "ComboboxControl",
    "ComboboxInput",
    "ComboboxLabel",
    "ComboboxOption",
    "ComboboxPositioner",
    "ComboboxTrigger",
  ],
  dialog: [
    "Dialog",
    "DialogBackdrop",
    "DialogCloseTrigger",
    "DialogContainer",
    "DialogContent",
    "DialogDescription",
    "DialogTitle",
    "DialogTrigger",
  ],
  editable: [
    "Editable",
    "EditableArea",
    "EditableCancelTrigger",
    "EditableControl",
    "EditableEditTrigger",
    "EditableInput",
    "EditableLabel",
    "EditablePreview",
    "EditableSubmitTrigger",
  ],
  environment: ["Environment"],
  "hover-card": [
    "HoverCard",
    "HoverCardArrow",
    "HoverCardArrowTip",
    "HoverCardContent",
    "HoverCardPositioner",
    "HoverCardTrigger",
  ],
  menu: [
    "Menu",
    "MenuArrow",
    "MenuArrowTip",
    "MenuContent",
    "MenuContextTrigger",
    "MenuItem",
    "MenuItemGroup",
    "MenuItemGroupLabel",
    "MenuOptionItem",
    "MenuPositioner",
    "MenuSeparator",
    "MenuTrigger",
    "MenuTriggerItem",
  ],
  "number-input": [
    "NumberInput",
    "NumberInputControl",
    "NumberInputDecrementTrigger",
    "NumberInputField",
    "NumberInputIncrementTrigger",
    "NumberInputLabel",
    "NumberInputScrubber",
  ],
  pagination: [
    "Pagination",
    "PaginationEllipsis",
    "PaginationList",
    "PaginationListItem",
    "PaginationNextPageTrigger",
    "PaginationPageTrigger",
    "PaginationPrevPageTrigger",
  ],
  "pin-input": [
    "PinInput",
    "PinInputControl",
    "PinInputField",
    "PinInputLabel",
  ],
  popover: [
    "Popover",
    "PopoverAnchor",
    "PopoverArrow",
    "PopoverArrowTip",
    "PopoverCloseTrigger",
    "PopoverContent",
    "PopoverDescription",
    "PopoverPositioner",
    "PopoverTitle",
    "PopoverTrigger",
  ],
  pressable: ["Pressable"],
  "radio-group": [
    "Radio",
    "RadioControl",
    "RadioGroup",
    "RadioGroupLabel",
    "RadioInput",
    "RadioLabel",
  ],
  "range-slider": [
    "RangeSlider",
    "RangeSliderControl",
    "RangeSliderLabel",
    "RangeSliderMarker",
    "RangeSliderMarkerGroup",
    "RangeSliderOutput",
    "RangeSliderRange",
    "RangeSliderThumb",
    "RangeSliderTrack",
  ],
  "rating-group": [
    "Rating",
    "RatingGroup",
    "RatingGroupControl",
    "RatingGroupLabel",
  ],
  select: [
    "Select",
    "SelectContent",
    "SelectLabel",
    "SelectOption",
    "SelectOptionGroup",
    "SelectOptionGroupLabel",
    "SelectPositioner",
    "SelectTrigger",
  ],
  slider: [
    "Slider",
    "SliderControl",
    "SliderLabel",
    "SliderMarker",
    "SliderMarkerGroup",
    "SliderOutput",
    "SliderRange",
    "SliderThumb",
    "SliderTrack",
  ],
  splitter: ["Splitter", "SplitterPanel", "SplitterResizeTrigger"],
  tabs: ["TabContent", "TabIndicator", "TabList", "TabTrigger", "Tabs"],
  "tags-input": [
    "Tag",
    "TagDeleteTrigger",
    "TagInput",
    "TagsInput",
    "TagsInputClearTrigger",
    "TagsInputControl",
    "TagsInputField",
    "TagsInputLabel",
  ],
  toast: [
    "Toast",
    "ToastCloseTrigger",
    "ToastDescription",
    "ToastGroup",
    "ToastPlacements",
    "ToastProvider",
    "ToastTitle",
  ],
  tooltip: [
    "Tooltip",
    "TooltipArrow",
    "TooltipArrowTip",
    "TooltipContent",
    "TooltipPositioner",
    "TooltipTrigger",
  ],
};
